version : '3.9'
services:
  database:
    image: postgres:15
    container_name: wallet-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: mini-digital-wallet
    ports:
      - "5432:5432"
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: